[project]
name = "ipilot"
version = "0.0.0"
description = "IP Information Lookup Tool"
readme = "README.md"
authors = [
    {name = "Luke Tainton", email = "luke@tainton.uk"},
]
requires-python = "<4.0,>=3.11"

dependencies = [
    "requests==2.32.5",
    "tabulate==0.9.0",
]

[project.scripts]
app = "app.main:main"

[dependency-groups]
dev = [
    "black<25.11.1,>=25.11.0",
    "coverage<8.0.0,>=7.5.0",
    "pylint<4.1.0,>=4.0.4",
    "pylint-exit<2.0.0,>=1.2.0",
    "pytest<9.1.0,>=9.0.0",
    "requests-mock<2.0.0,>=1.12.1",
]

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
